name: app_serving_doctors
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^9.1.1
  #Code Generation
  freezed: ^3.2.3
  # Annotations for the freezed code-generator. 
  # This package does nothing without freezed too.
  freezed_annotation: ^3.1.0
  # For Dependency Injection
  get_it: ^8.2.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.11.1
  # Classes and helper functions that support JSON code generation
  # via the `json_serializable` package.
  json_annotation: ^4.9.0
  # Networking
  dio: ^5.9.0
  retrofit: ^4.8.0
  retrofit_generator: ^10.0.6
  pretty_dio_logger: ^1.4.0
  flutter_native_splash: ^2.4.7
  #

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  easy_localization: ^3.0.8
  # Vector Image
  flutter_svg: ^2.0.18
  # for adapting the app to different screen sizes & font sizes
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true